name: Deploy Dev

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy-dev:
    name: Deploy Dev
    uses: ./.github/workflows/deploy-reusable.yml
    with:
      deploy_files: all
      environment: prod
      project_environment: dev
      public_base_url_kind: dev
      server_dir: dev/
    secrets: inherit
