name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy-dev:
    name: Deploy Dev
    uses: ./.github/workflows/deploy-reusable.yml
    with:
      environment: prod
      project_environment: dev
      server_dir: dev/
    secrets: inherit
